### ISSUE TITLE
Setup Code for Computer Vision (Open CV)

### ISSUE THREAD

**Issue by Nels27** [SearchAndTagBot/SrcCode#2]
Getting the OpenCV to run on the RPi 3 with the V2 camera

**Comment by efuller3** [comment]
link for CV install instructions: www.life2coding.com/install-opencv-3-4-0-python-3-raspberry-pi-3/

**Comment by Nels27** [comment]
We can pursue google cloud services as an alternative if this OpenCV does not work.
https://www.dexterindustries.com/howto/use-google-cloud-vision-on-the-raspberry-pi/

**Comment by Nels27** [comment]
Since the Open CV installation caused the PiCamera not to work we will be defaulting to using the google cloud vision instead.
