### ISSUE TITLE
Presentation Material

### ISSUE THREAD

**Issue by efuller3** [SearchAndTagBot/SrcCode#9]
https://docs.google.com/presentation/d/1r4cLufTsa1ciTToAlC9ou0CbInqPyBWMr1U4Mzn_Wwk/edit?usp=sharing

"I would suggest slides something like:  project name (same as web page title) with team member names, a short description of the project idea perhaps with a block diagram and parts list. Another slide on software used and developed for the project (perhaps using a Gantt chart). A demo video or photo, and a summary of results and ideas for further work. Each team member must present a portion of the presentation."

**Comment by Nels27** [comment]
Completed slide is located here [https://drive.google.com/open?id=19oWzslykEf3nBsgVavCj8GriQ089Vi7u](url)
